Suppress warning when calling repr of empty GeoSeries. Fixes #1647
geopandas/geopandas pull request #1673
Opened 2020-11-01 21:35 UTC by gcaria

The lines I've added suppress the warning when calling both `__repr__` and `total_bounds`.
This is not exactly what was asked in the issue, but I have noticed that `total_bounds` could already return silently nans before this edit.

Maybe a warning message about returning nans can be printed for both cases ?

2020-11-02 11:57 UTC, martinfleis requested changes
Thanks for working on it. I think that we don't have to touch `total_bounds` code here. Instead, we should explicitly suppress this warning when calling `__repr__`. The existing warning you get for `total_bounds` with empty geoms is meaningful and should be kept.

2020-11-02 14:08 UTC, gcaria commented
Just to make I understand, the fact that `total_bounds` can already return silently nans (line 705) is not a problem, correct ?

2020-11-07 20:34 UTC, martinfleis commented
It is not a problem. That happens for an empty geodataframe, it is expected in such a case.

2020-11-09 13:44 UTC, gcaria commented
Understood, it should be correctly suppressed now, please have a look :)

2020-11-22 22:00 UTC, martinfleis approved these changes
Thanks!

2020-11-22 22:02 UTC, martinfleis commented
I am going to merge this but at the same time I will open an issue aiming to remove this part altogether and use `crs.is_geographic` / `crs.is_projected` instead because that is what this heuristics is trying to do anyway.

2020-11-22 22:02 UTC, merged

2020-11-23 07:49 UTC, jorisvandenbossche commented
Thanks @gcaria !