Fix unwaranted warning with read_file when file contains multiple layers and both layer and bbox or mask arguments are used.
geopandas/geopandas pull request #3378
Opened 2024-07-12 18:21 UTC by FredericF

Pass down the layer argument from gpd.read_file to pyogrio.read_info to prevent the unwaranted warning "More than one layer found in [file]. Specify layer parameter to avoid this warning.unwaranted warnings about ". when the layer argument is actually specified.

2024-07-15 12:35 UTC, m-richards requested changes
Thanks for reporting this and providing a fix @FredericF! Would you be able to add a regression test to 
geopandas/io/tests/test_file.py (say taking your example from the issue) to ensure we make sure this keeps working in the future?

You can put the `read_file` call inside a 
```python
with warnings.catch_warnings():
    warnings.simplefilter("error")
```
block to make sure no warnings are shown.

2024-07-19 20:36 UTC, FredericF commented
Hello @m-richards, I added a test.

2024-07-21 05:58 UTC, m-richards approved these changes
Thanks @FredericF for this, looking good now!

I've just pushed a couple of commits to make this test explicit on the engines being tested given we see this specifically with pyogrio (test is run against fiona too where installed, but that's fine) and a changelog entry - normally I'd leave that to you, but there's no heading to place under given we've just done a release.

2024-08-15 09:39 UTC, martinfleis approved these changes
One minor nit on the changelog. Thanks!

2024-08-15 09:39 UTC, martinfleis commented on CHANGELOG.md
> +- Fix unspecified layer warning being emitted reading multilayer datasets, even
```suggestion
- Fix unspecified layer warning being emitted while reading multilayer datasets, even
```

2024-08-15 09:53 UTC, merged